build: false

environment:   
    PYTHON_HOME: "C:\\Python37"

    CONAN_REMOTES: "https://api.bintray.com/conan/conan-community/conan,https://api.bintray.com/conan/bincrafters/public-conan,https://api.bintray.com/conan/vthiery/conan-packages"

    global:
       # Avoid long paths on Windows
       STACK_ROOT: "c:\\s"
       STACK_WORK: ".w"
       WORK_DIR: "c:\\w"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release

install:
    - set TEST_VAR=Hello, world!
    - echo before reboot
    - ps: Restart-Computer -Force            # here the server goes restarting
    - echo Before sleep
    - ps: |
        Write-Host $env:TEST_VAR
        Write-Host ([datetime]::Now)
        Start-Sleep -s 10
        Write-Host "After sleep"
        Write-Host ([datetime]::Now)

build_script:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
