# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- stable/1.1.0

pool:
  vmImage: 'vs2017-win2016'

variables:
    CONAN_VISUAL_VERSIONS: 15
    CONAN_BUILD_TYPES: Release

steps:
- powershell: |
  Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
  Restart-Computer -Force -Verbose

- script: |
    set PATH=%PATH%;%PYTHON%/Scripts/
    pip.exe install conan --upgrade
    pip.exe install conan_package_tools bincrafters_package_tools
    conan user # It creates the conan data directory
    python build.py
  displayName: Installing conan and building package
